### ISSUE TITLE
Snippets working just in .js files

### ISSUE THREAD

**Issue by scherman** [evanplaice/angular2-snippets#4]
As the title says, it's happening to me that i can use the snippets just in files which has ".js" extension. But using TypeScript i want to put the snippets in ".ts" files instead of ".js". 

Do you know how to fix this?

**Comment by evanplaice** [comment]
Oh... right. I guess that'll only work for the .5% of users like me who use use angular2 + ES6. The snippets are designed to work with both TS and ES6 (ie with decorators/annotations enabled via Babel/Traceur).

To add Typescript support, the snippets/completions scope needs to be modified to include `source.ts`.

_Source:_
- [Sublime 3 JS Snippets to Typescript](http://stackoverflow.com/q/30914027/290340)

Feel free to submit a PR with the fix, otherwise I'll get to it soon.

**Comment by evanplaice** [comment]
@scherman Typescript support has been added in the latest.

Ref: 4ac2ad14
